---
- hosts: all
  gather_facts: false
  tasks:
    - name: Update system
      package:
        name: "*"
        state: latest

    - name: Install dependencies
      package:
        name: {{ item }}
        state: present
      with_items:
        - python
        - unzip

    - name: Create tmp directory
      tempfile:
        state: directory
        prefix: aws-cli-v2
      register: tmp_path

    - name: Download aws-cli-v2 archive
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "{{ tmp_path.path }}/awscliv2.zip"
      register: aws_cli_download

    - name: Unzip aws-cli-v2 archive
      unarchive:
        src: "{{ tmp_path.path }}/awscliv2.zip"
        dest: "{{ tmp_path.path }}"
        copy: no
        creates: "{{ tmp_path.path }}/awscli-bundle"
      when: aws_cli_download.changed

  
